### PR TITLE
fix json marshaling of f5 node.

### PR DESCRIPTION
**Pull request by jaloren**
The bigip REST API returns a json document for node where the shape has nested fields fqdn.interval. The interval is an int. However, the node struct expects the field to be a string.

Fix is to set the data from a string to an int.

### CODE REVIEW

**Comment by jaloren** [comment]
I believe the reason there are so many additional changes  is because of go fmt.

**Comment by scshitole** [comment]
@jaloren thanks

**Comment by scshitole** [comment]
@jaloren I am getting this error after the pull request
=== RUN   TestAccBigipLtmNode_create
--- FAIL: TestAccBigipLtmNode_create (2.26s)
	testing.go:513: Step 0 error: Error applying: 1 error occurred:
		
		* bigip_ltm_node.test-node: 1 error occurred:
		
		* bigip_ltm_node.test-node: json: cannot unmarshal string into Go struct field .interval of type int
	testing.go:573: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Error refreshing: 1 error occurred:
		
		* bigip_ltm_node.test-node: 1 error occurred:
		
		* bigip_ltm_node.test-node: bigip_ltm_node.test-node: json: cannot unmarshal string into Go struct field .interval of type int
		
		State: <nil>
	testing.go:513: Step 0 error: Error applying: 1 error occurred:
		
		* bigip_ltm_node.test-fqdn-node: 1 error occurred:

**Comment by scshitole** [comment]
@jaloren please ignore I had residual config in my bigip, the fix is fine

**Comment by scshitole** [comment]
@jaloren sorry for going back and forth, when I change from it does fails, 
=== RUN   TestAccBigipLtmNode_create
--- FAIL: TestAccBigipLtmNode_create (3.58s)
	testing.go:513: Step 0 error: Error applying: 1 error occurred:
		
		* bigip_ltm_node.test-node: 1 error occurred:
		
		* bigip_ltm_node.test-node: json: cannot unmarshal string into Go struct field .interval of type int
	testing.go:573: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

**Comment by scshitole** [comment]
@jaloren  when I change back from "int" to "string" it passes. Here is my test file
package bigip

import (
	"fmt"
	"testing"

	"github.com/f5devcentral/go-bigip"
	"github.com/hashicorp/terraform/helper/resource"
	"github.com/hashicorp/terraform/terraform"
)

var TEST_NODE_NAME = fmt.Sprintf("/%s/test-node", TEST_PARTITION)
var TEST_FQDN_NODE_NAME = fmt.Sprintf("/%s/test-fqdn-node", TEST_PARTITION)

var TEST_NODE_RESOURCE = `
resource "bigip_ltm_node" "test-node" {
	name = "` + TEST_NODE_NAME + `"
	address = "10.10.10.10"
	connection_limit = "0"
	dynamic_ratio = "1"
	monitor = "default"
	rate_limit = "disabled"
}
`
var TEST_FQDN_NODE_RESOURCE = `
resource "bigip_ltm_node" "test-fqdn-node" {
	name = "` + TEST_FQDN_NODE_NAME + `"
	address = "f5.com"
	connection_limit = "0"
	dynamic_ratio = "1"
	monitor = "default"
	rate_limit = "disabled"
}
`

func TestAccBigipLtmNode_create(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAcctPreCheck(t)
		},
		Providers:    testAccProviders,
		CheckDestroy: testCheckNodesDestroyed,
		Steps: []resource.TestStep{
			{
				Config: TEST_NODE_RESOURCE,
				Check: resource.ComposeTestCheckFunc(
					testCheckNodeExists(TEST_NODE_NAME, true),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-node", "name", TEST_NODE_NAME),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-node", "address", "10.10.10.10"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-node", "connection_limit", "0"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-node", "dynamic_ratio", "1"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-node", "monitor", "default"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-node", "rate_limit", "disabled"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-node", "state", "user-up"),
				),
			},
		},
	})

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAcctPreCheck(t)
		},
		Providers:    testAccProviders,
		CheckDestroy: testCheckNodesDestroyed,
		Steps: []resource.TestStep{
			{
				Config: TEST_FQDN_NODE_RESOURCE,
				Check: resource.ComposeTestCheckFunc(
					testCheckNodeExists(TEST_FQDN_NODE_NAME, true),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-fqdn-node", "name", TEST_FQDN_NODE_NAME),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-fqdn-node", "address", "f5.com"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-fqdn-node", "connection_limit", "0"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-fqdn-node", "dynamic_ratio", "1"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-fqdn-node", "monitor", "default"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-fqdn-node", "rate_limit", "disabled"),
					resource.TestCheckResourceAttr("bigip_ltm_node.test-fqdn-node", "state", "user-up"),
				),
			},
		},
	})
}

func TestAccBigipLtmNode_import(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAcctPreCheck(t)
		},
		Providers:    testAccProviders,
		CheckDestroy: testCheckNodesDestroyed,
		Steps: []resource.TestStep{
			{
				Config: TEST_NODE_RESOURCE,
				Check: resource.ComposeTestCheckFunc(
					testCheckNodeExists(TEST_NODE_NAME, true),
				),
				ResourceName:      TEST_NODE_NAME,
				ImportState:       false,
				ImportStateVerify: true,
			},
		},
	})

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAcctPreCheck(t)
		},
		Providers:    testAccProviders,
		CheckDestroy: testCheckNodesDestroyed,
		Steps: []resource.TestStep{
			{
				Config: TEST_FQDN_NODE_RESOURCE,
				Check: resource.ComposeTestCheckFunc(
					testCheckNodeExists(TEST_FQDN_NODE_NAME, true),
				),
				ResourceName:      TEST_FQDN_NODE_NAME,
				ImportState:       false,
				ImportStateVerify: true,
			},
		},
	})
}


func testCheckNodeExists(name string, exists bool) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		client := testAccProvider.Meta().(*bigip.BigIP)

		node, err := client.GetNode(name)
		if err != nil {
			return err
		}
		if exists && node == nil {
			return fmt.Errorf("Node %s was not created.", name)
		}
		if !exists && node != nil {
			return fmt.Errorf("Node %s still exists.", name)
		}
		return nil
	}
}

func testCheckNodesDestroyed(s *terraform.State) error {
	client := testAccProvider.Meta().(*bigip.BigIP)

	for _, rs := range s.RootModule().Resources {
		if rs.Type != "bigip_ltm_node" {
			continue
		}

		name := rs.Primary.ID
		node, err := client.GetNode(name)
		if err != nil {
			return err
		}
		if node != nil {
			return fmt.Errorf("Node %s not destroyed.", name)
		}
	}
	return nil
}

**Comment by jaloren** [comment]
@scshitole could this be related to the version of the f5 each of us is testing against? I am using f5 ltm version 11.6.0. When curl the icontrol rest api directly, this is the json document returned for a node. If you curl your version of the f5 to get a list of nodes, what does the json document look like? Is the interval a string or a number?


```
{
  "kind": "tm:ltm:node:nodestate",
  "name": "10.10.10.27",
  "partition": "Common",
  "fullPath": "/Common/X.X.X.X",
  "generation": 1,
  "selfLink": "https://localhost/mgmt/tm/ltm/node/~Common~10.10.10.27?ver=11.6.0",
  "address": "X.X.X.X",
  "connectionLimit": 0,
  "description": "term3",
  "dynamicRatio": 1,
  "ephemeral": "false",
  "fqdn": {
    "addressFamily": "ipv4",
    "autopopulate": "disabled",
    "downInterval": 5,
    "interval": 3600
  },
  "logging": "disabled",
  "monitor": "default",
  "rateLimit": "disabled",
  "ratio": 1,
  "session": "user-enabled",
  "state": "unchecked"
}
```

**Comment by scshitole** [comment]
@jaloren 
The documentation says string, below is cut and paste from doc

 
image

**Comment by scshitole** [comment]
@jaloren I am using 12.X version, 11.6 is pretty old and now no longer supported

**Comment by jaloren** [comment]
@scshitole Okay good to know. While I understand that 12.X and later is supported, I could submit a separate PR that would handle decoding for either case. It would just require a custom JSONUnmarshaling func for this field.

Would this be something you'd consider accepting?

**Comment by scshitole** [comment]
Sure that makes sense please go ahead

**Pull request merged**
