### PR TITLE
Adding GetVlanInterfaces method

### PR DESCRIPTION
**Pull request by dannyk81**
New struct and method to retrieve a list of Interfaces associated to a named vlan.

### CODE REVIEW

**Comment by dannyk81** [comment]
🚀 @scshitole **This must be merged before** https://github.com/f5devcentral/terraform-provider-bigip/pull/126 !!! and vendoring updated afterwards.

**Comment by dannyk81** [comment]
@scshitole 

Sure, let me run it now, will post results shortly.

**Comment by dannyk81** [comment]
@scshitole test results below, I'm getting failures in a couple of `PersistenceProfile` resources:

```
=== RUN   TestAccBigipLtmPersistenceProfileCookieCreate
--- FAIL: TestAccBigipLtmPersistenceProfileCookieCreate (3.99s)
        testing.go:527: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: bigip_ltm_persistence_profile_cookie.test_ppcookie
                  app_service: "" => "none"
```

But I haven't touched the code around this... maybe this is due to this commit --> https://github.com/terraform-providers/terraform-provider-bigip/commit/344b1fe5d026bb3102d81b8405a4804112287f1e ??

Here's the test result:
```
=== RUN   TestAccProvider
--- PASS: TestAccProvider (0.01s)
=== RUN   TestAccBigipCmDevice_create
--- PASS: TestAccBigipCmDevice_create (5.16s)
=== RUN   TestAccBigipCmDevice_import
--- PASS: TestAccBigipCmDevice_import (4.78s)
=== RUN   TestAccBigipCmDevicegroup_create
--- PASS: TestAccBigipCmDevicegroup_create (6.13s)
=== RUN   TestAccBigipCmDevicegroup_import
--- PASS: TestAccBigipCmDevicegroup_import (6.01s)
=== RUN   TestAccBigipLtmDataGroup_create
--- PASS: TestAccBigipLtmDataGroup_create (15.23s)
=== RUN   TestAccBigipLtmDataGroup_import
--- PASS: TestAccBigipLtmDataGroup_import (15.34s)
=== RUN   TestAccBigipLtmIRule_create
--- PASS: TestAccBigipLtmIRule_create (5.00s)
=== RUN   TestAccBigipLtmIRule_import
--- PASS: TestAccBigipLtmIRule_import (5.08s)
=== RUN   TestAccBigipLtmMonitor_create
--- PASS: TestAccBigipLtmMonitor_create (10.66s)
=== RUN   TestAccBigipLtmMonitor_import
--- PASS: TestAccBigipLtmMonitor_import (10.63s)
=== RUN   TestAccBigipLtmNode_create
--- PASS: TestAccBigipLtmNode_create (10.13s)
=== RUN   TestAccBigipLtmNode_import
--- PASS: TestAccBigipLtmNode_import (10.04s)
=== RUN   TestAccBigipLtmNodeInvalid
--- PASS: TestAccBigipLtmNodeInvalid (0.01s)
=== RUN   TestAccBigipLtmNodeCreate
--- PASS: TestAccBigipLtmNodeCreate (0.08s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieCreate
--- FAIL: TestAccBigipLtmPersistenceProfileCookieCreate (3.99s)
        testing.go:527: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: bigip_ltm_persistence_profile_cookie.test_ppcookie
                  app_service: "" => "none"

                STATE:

                bigip_ltm_persistence_profile_cookie.test_ppcookie:
                  ID = /Common/test-ppcookie
                  provider = provider.bigip
                  always_send = enabled
                  app_service =
                  cookie_encryption = disabled
                  cookie_encryption_passphrase =
                  cookie_name = ham
                  defaults_from = /Common/cookie
                  expiration = 1:0:0
                  hash_length = 0
                  hash_offset = 0
                  httponly = disabled
                  match_across_pools = enabled
                  match_across_services = enabled
                  match_across_virtuals = enabled
                  mirror = disabled
                  name = /Common/test-ppcookie
                  override_conn_limit = enabled
                  timeout = 3600
=== RUN   TestAccBigipLtmPersistenceProfileCookieImport
--- FAIL: TestAccBigipLtmPersistenceProfileCookieImport (4.10s)
        testing.go:527: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: bigip_ltm_persistence_profile_cookie.test_ppcookie
                  app_service: "" => "none"

                STATE:

                bigip_ltm_persistence_profile_cookie.test_ppcookie:
                  ID = /Common/test-ppcookie
                  provider = provider.bigip
                  always_send = enabled
                  app_service =
                  cookie_encryption = disabled
                  cookie_encryption_passphrase =
                  cookie_name = ham
                  defaults_from = /Common/cookie
                  expiration = 1:0:0
                  hash_length = 0
                  hash_offset = 0
                  httponly = disabled
                  match_across_pools = enabled
                  match_across_services = enabled
                  match_across_virtuals = enabled
                  mirror = disabled
                  name = /Common/test-ppcookie
                  override_conn_limit = enabled
                  timeout = 3600
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrCreate
--- FAIL: TestAccBigipLtmPersistenceProfileDstAddrCreate (4.62s)
        testing.go:527: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: bigip_ltm_persistence_profile_dstaddr.test_ppdstaddr
                  app_service: "" => "none"

                STATE:

                bigip_ltm_persistence_profile_dstaddr.test_ppdstaddr:
                  ID = /Common/test-ppdstaddr
                  provider = provider.bigip
                  app_service =
                  defaults_from = /Common/dest_addr
                  hash_algorithm = carp
                  mask = 255.255.255.255
                  match_across_pools = enabled
                  match_across_services = enabled
                  match_across_virtuals = enabled
                  mirror = enabled
                  name = /Common/test-ppdstaddr
                  override_conn_limit = enabled
                  timeout = 3600
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrImport
--- FAIL: TestAccBigipLtmPersistenceProfileDstAddrImport (4.02s)
        testing.go:527: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: bigip_ltm_persistence_profile_dstaddr.test_ppdstaddr
                  app_service: "" => "none"

                STATE:

                bigip_ltm_persistence_profile_dstaddr.test_ppdstaddr:
                  ID = /Common/test-ppdstaddr
                  provider = provider.bigip
                  app_service =
                  defaults_from = /Common/dest_addr
                  hash_algorithm = carp
                  mask = 255.255.255.255
                  match_across_pools = enabled
                  match_across_services = enabled
                  match_across_virtuals = enabled
                  mirror = enabled
                  name = /Common/test-ppdstaddr
                  override_conn_limit = enabled
                  timeout = 3600
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrCreate
--- FAIL: TestAccBigipLtmPersistenceProfileSrcAddrCreate (4.13s)
        testing.go:527: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: bigip_ltm_persistence_profile_srcaddr.test_ppsrcaddr
                  app_service: "" => "none"

                STATE:

                bigip_ltm_persistence_profile_srcaddr.test_ppsrcaddr:
                  ID = /Common/test-ppsrcaddr
                  provider = provider.bigip
                  app_service =
                  defaults_from = /Common/source_addr
                  hash_algorithm = carp
                  map_proxies = enabled
                  mask = 255.255.255.255
                  match_across_pools = enabled
                  match_across_services = enabled
                  match_across_virtuals = enabled
                  mirror = enabled
                  name = /Common/test-ppsrcaddr
                  override_conn_limit = enabled
                  timeout = 3600
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrImport
--- FAIL: TestAccBigipLtmPersistenceProfileSrcAddrImport (4.17s)
        testing.go:527: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: bigip_ltm_persistence_profile_srcaddr.test_ppsrcaddr
                  app_service: "" => "none"

                STATE:

                bigip_ltm_persistence_profile_srcaddr.test_ppsrcaddr:
                  ID = /Common/test-ppsrcaddr
                  provider = provider.bigip
                  app_service =
                  defaults_from = /Common/source_addr
                  hash_algorithm = carp
                  map_proxies = enabled
                  mask = 255.255.255.255
                  match_across_pools = enabled
                  match_across_services = enabled
                  match_across_virtuals = enabled
                  mirror = enabled
                  name = /Common/test-ppsrcaddr
                  override_conn_limit = enabled
                  timeout = 3600
=== RUN   TestAccBigipLtmPersistenceProfileSSLCreate
--- PASS: TestAccBigipLtmPersistenceProfileSSLCreate (5.55s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLImport
--- PASS: TestAccBigipLtmPersistenceProfileSSLImport (5.55s)
=== RUN   TestAccBigipLtmPolicy_create
--- PASS: TestAccBigipLtmPolicy_create (9.03s)
=== RUN   TestAccBigipLtmPolicy_import
--- PASS: TestAccBigipLtmPolicy_import (10.14s)
=== RUN   TestAccBigipLtmPool_create
--- PASS: TestAccBigipLtmPool_create (9.91s)
=== RUN   TestAccBigipLtmPool_import
--- PASS: TestAccBigipLtmPool_import (10.76s)
=== RUN   TestAccBigipLtmfasthttp_create
--- PASS: TestAccBigipLtmfasthttp_create (8.51s)
=== RUN   TestAccBigipLtmProfilefasthttp_import
--- PASS: TestAccBigipLtmProfilefasthttp_import (5.09s)
=== RUN   TestAccBigipLtmProfileFastl4_create
--- PASS: TestAccBigipLtmProfileFastl4_create (4.78s)
=== RUN   TestAccBigipLtmProfileFastl4_import
--- PASS: TestAccBigipLtmProfileFastl4_import (4.76s)
=== RUN   TestAccBigipLtmProfileHttp2_create
--- PASS: TestAccBigipLtmProfileHttp2_create (4.75s)
=== RUN   TestAccBigipLtmProfileHttp2_import
--- PASS: TestAccBigipLtmProfileHttp2_import (4.74s)
=== RUN   TestAccBigipLtmProfileHttpcompress_create
--- PASS: TestAccBigipLtmProfileHttpcompress_create (4.79s)
=== RUN   TestAccBigipLtmProfileHttpcompress_import
--- PASS: TestAccBigipLtmProfileHttpcompress_import (4.85s)
=== RUN   TestAccBigipLtmProfileoneconnect_create
--- PASS: TestAccBigipLtmProfileoneconnect_create (4.79s)
=== RUN   TestAccBigipLtmProfileoneconnect_import
--- PASS: TestAccBigipLtmProfileoneconnect_import (4.86s)
=== RUN   TestAccBigipLtmProfileTcp_create
--- PASS: TestAccBigipLtmProfileTcp_create (4.83s)
=== RUN   TestAccBigipLtmProfileTcp_import
--- PASS: TestAccBigipLtmProfileTcp_import (4.78s)
=== RUN   TestAccBigipLtmsnat_create
--- PASS: TestAccBigipLtmsnat_create (4.78s)
=== RUN   TestAccBigipLtmsnat_import
--- PASS: TestAccBigipLtmsnat_import (4.96s)
=== RUN   TestAccBigipLtmsnatpool_create
--- PASS: TestAccBigipLtmsnatpool_create (4.74s)
=== RUN   TestAccBigipLtmsnatpool_import
--- PASS: TestAccBigipLtmsnatpool_import (4.81s)
=== RUN   TestAccBigipLtmVA_create
--- PASS: TestAccBigipLtmVA_create (5.02s)
=== RUN   TestAccBigipLtmVA_import
--- PASS: TestAccBigipLtmVA_import (5.03s)
=== RUN   TestAccBigipLtmVS_create
--- PASS: TestAccBigipLtmVS_create (8.89s)
=== RUN   TestAccBigipLtmVS_import
--- PASS: TestAccBigipLtmVS_import (8.81s)
=== RUN   TestAccBigipNetroute_create
--- PASS: TestAccBigipNetroute_create (7.02s)
=== RUN   TestAccBigipNetroute_import
--- PASS: TestAccBigipNetroute_import (6.94s)
=== RUN   TestAccBigipNetselfip_create
--- PASS: TestAccBigipNetselfip_create (7.45s)
=== RUN   TestAccBigipNetselfip_import
--- PASS: TestAccBigipNetselfip_import (14.84s)
=== RUN   TestAccBigipNetvlan_create
--- PASS: TestAccBigipNetvlan_create (7.33s)
=== RUN   TestAccBigipNetvlan_import
--- PASS: TestAccBigipNetvlan_import (7.40s)
=== RUN   TestAccBigipSysdns_create
--- PASS: TestAccBigipSysdns_create (5.14s)
=== RUN   TestAccBigipSysdns_import
--- PASS: TestAccBigipSysdns_import (5.02s)
=== RUN   TestAccBigipSysIapp_create
--- PASS: TestAccBigipSysIapp_create (5.11s)
=== RUN   TestAccBigipSysIapp_import
--- PASS: TestAccBigipSysIapp_import (5.03s)
=== RUN   TestAccBigipSysNtp_create
--- PASS: TestAccBigipSysNtp_create (5.05s)
=== RUN   TestAccBigipSysNtp_import
--- PASS: TestAccBigipSysNtp_import (5.07s)
=== RUN   TestAccBigipSysNtpInvalid
--- PASS: TestAccBigipSysNtpInvalid (0.02s)
=== RUN   TestAccBigipSysProvision_create
--- PASS: TestAccBigipSysProvision_create (4.38s)
=== RUN   TestAccBigipSysProvision_import
--- PASS: TestAccBigipSysProvision_import (4.84s)
=== RUN   TestAccBigipSyssnmp_create
--- PASS: TestAccBigipSyssnmp_create (5.39s)
=== RUN   TestAccBigipSyssnmp_import
--- PASS: TestAccBigipSyssnmp_import (5.18s)
FAIL
FAIL    github.com/f5devcentral/terraform-provider-bigip/bigip  390.112s
```

**Comment by scshitole** [comment]
@dannyk81  which image you are using ? there is a change in the F5 code, with 13.0 image your fix should pass.

**Comment by dannyk81** [comment]
@scshitole I use 12.1.1

**Comment by scshitole** [comment]
@dannyk81 there was change in F5 code 13.0 so I have to change the test files for profiles

**Comment by dannyk81** [comment]
@scshitole I see, but is this affecting only tests? or this will also have impact when provisioning these resource on a BigIP 12.1.1?

In the README we claim that this suite was tested with 12.1.1, looks like this is no longer the case.

**Comment by scshitole** [comment]
@dannyk81 this is only test files rest is fine, I ran the tests with 13.0 after your fix
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-bigip	[no test files]
=== RUN   TestAccProvider
--- PASS: TestAccProvider (0.00s)
=== RUN   TestAccBigipCmDevice_create
--- PASS: TestAccBigipCmDevice_create (4.41s)
=== RUN   TestAccBigipCmDevice_import
--- PASS: TestAccBigipCmDevice_import (3.08s)
=== RUN   TestAccBigipCmDevicegroup_create
--- PASS: TestAccBigipCmDevicegroup_create (3.05s)
=== RUN   TestAccBigipCmDevicegroup_import
--- PASS: TestAccBigipCmDevicegroup_import (2.36s)
=== RUN   TestAccBigipLtmDataGroup_create
--- PASS: TestAccBigipLtmDataGroup_create (8.69s)
=== RUN   TestAccBigipLtmDataGroup_import
--- PASS: TestAccBigipLtmDataGroup_import (8.25s)
=== RUN   TestAccBigipLtmIRule_create
--- PASS: TestAccBigipLtmIRule_create (3.20s)
=== RUN   TestAccBigipLtmIRule_import
--- PASS: TestAccBigipLtmIRule_import (2.99s)
=== RUN   TestAccBigipLtmMonitor_create
--- PASS: TestAccBigipLtmMonitor_create (3.06s)
=== RUN   TestAccBigipLtmMonitor_import
--- PASS: TestAccBigipLtmMonitor_import (2.77s)
=== RUN   TestAccBigipLtmNode_create
--- PASS: TestAccBigipLtmNode_create (5.41s)
=== RUN   TestAccBigipLtmNode_import
--- PASS: TestAccBigipLtmNode_import (6.35s)
=== RUN   TestAccBigipLtmNodeInvalid
--- PASS: TestAccBigipLtmNodeInvalid (0.01s)
=== RUN   TestAccBigipLtmNodeCreate
--- PASS: TestAccBigipLtmNodeCreate (0.02s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieCreate
--- PASS: TestAccBigipLtmPersistenceProfileCookieCreate (2.83s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieImport
--- PASS: TestAccBigipLtmPersistenceProfileCookieImport (1.92s)
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrCreate
--- PASS: TestAccBigipLtmPersistenceProfileDstAddrCreate (3.59s)
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrImport
--- PASS: TestAccBigipLtmPersistenceProfileDstAddrImport (2.75s)
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrCreate
--- PASS: TestAccBigipLtmPersistenceProfileSrcAddrCreate (2.74s)
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrImport
--- PASS: TestAccBigipLtmPersistenceProfileSrcAddrImport (2.95s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLCreate
--- PASS: TestAccBigipLtmPersistenceProfileSSLCreate (3.08s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLImport
--- PASS: TestAccBigipLtmPersistenceProfileSSLImport (2.29s)
=== RUN   TestAccBigipLtmPolicy_create
--- PASS: TestAccBigipLtmPolicy_create (4.21s)
=== RUN   TestAccBigipLtmPolicy_import
--- PASS: TestAccBigipLtmPolicy_import (7.59s)
=== RUN   TestAccBigipLtmPool_create
--- PASS: TestAccBigipLtmPool_create (15.68s)
=== RUN   TestAccBigipLtmPool_import
--- PASS: TestAccBigipLtmPool_import (11.41s)
=== RUN   TestAccBigipLtmfasthttp_create
--- PASS: TestAccBigipLtmfasthttp_create (8.11s)
=== RUN   TestAccBigipLtmProfilefasthttp_import
--- PASS: TestAccBigipLtmProfilefasthttp_import (4.90s)
=== RUN   TestAccBigipLtmProfileFastl4_create
--- PASS: TestAccBigipLtmProfileFastl4_create (3.20s)
=== RUN   TestAccBigipLtmProfileFastl4_import
--- PASS: TestAccBigipLtmProfileFastl4_import (3.52s)
=== RUN   TestAccBigipLtmProfileHttp2_create
--- PASS: TestAccBigipLtmProfileHttp2_create (2.26s)
=== RUN   TestAccBigipLtmProfileHttp2_import
--- PASS: TestAccBigipLtmProfileHttp2_import (3.30s)
=== RUN   TestAccBigipLtmProfileHttpcompress_create
--- PASS: TestAccBigipLtmProfileHttpcompress_create (2.78s)
=== RUN   TestAccBigipLtmProfileHttpcompress_import
--- PASS: TestAccBigipLtmProfileHttpcompress_import (2.33s)
=== RUN   TestAccBigipLtmProfileoneconnect_create
--- PASS: TestAccBigipLtmProfileoneconnect_create (3.09s)
=== RUN   TestAccBigipLtmProfileoneconnect_import
--- PASS: TestAccBigipLtmProfileoneconnect_import (3.01s)
=== RUN   TestAccBigipLtmProfileTcp_create
--- PASS: TestAccBigipLtmProfileTcp_create (2.28s)
=== RUN   TestAccBigipLtmProfileTcp_import
--- PASS: TestAccBigipLtmProfileTcp_import (2.91s)
=== RUN   TestAccBigipLtmsnat_create
--- PASS: TestAccBigipLtmsnat_create (3.68s)
=== RUN   TestAccBigipLtmsnat_import
--- PASS: TestAccBigipLtmsnat_import (2.72s)
=== RUN   TestAccBigipLtmsnatpool_create
--- PASS: TestAccBigipLtmsnatpool_create (2.25s)
=== RUN   TestAccBigipLtmsnatpool_import
--- PASS: TestAccBigipLtmsnatpool_import (3.28s)
=== RUN   TestAccBigipLtmVA_create
--- PASS: TestAccBigipLtmVA_create (2.87s)
=== RUN   TestAccBigipLtmVA_import
--- PASS: TestAccBigipLtmVA_import (2.25s)
=== RUN   TestAccBigipLtmVS_create
--- PASS: TestAccBigipLtmVS_create (3.21s)
=== RUN   TestAccBigipLtmVS_import
--- PASS: TestAccBigipLtmVS_import (2.96s)
=== RUN   TestAccBigipNetroute_create
--- PASS: TestAccBigipNetroute_create (2.44s)
=== RUN   TestAccBigipNetroute_import
--- PASS: TestAccBigipNetroute_import (3.14s)
=== RUN   TestAccBigipNetselfip_create
--- PASS: TestAccBigipNetselfip_create (3.37s)
=== RUN   TestAccBigipNetselfip_import
--- PASS: TestAccBigipNetselfip_import (3.10s)
=== RUN   TestAccBigipNetvlan_create
--- PASS: TestAccBigipNetvlan_create (4.28s)
=== RUN   TestAccBigipNetvlan_import
--- PASS: TestAccBigipNetvlan_import (3.13s)
=== RUN   TestAccBigipSysdns_create
--- PASS: TestAccBigipSysdns_create (8.90s)
=== RUN   TestAccBigipSysdns_import
--- PASS: TestAccBigipSysdns_import (3.07s)
=== RUN   TestAccBigipSysIapp_create
--- PASS: TestAccBigipSysIapp_create (3.10s)
=== RUN   TestAccBigipSysIapp_import
--- PASS: TestAccBigipSysIapp_import (3.03s)
=== RUN   TestAccBigipSysNtp_create
--- PASS: TestAccBigipSysNtp_create (2.87s)
=== RUN   TestAccBigipSysNtp_import
--- PASS: TestAccBigipSysNtp_import (2.53s)
=== RUN   TestAccBigipSysNtpInvalid
--- PASS: TestAccBigipSysNtpInvalid (0.01s)
=== RUN   TestAccBigipSysProvision_create
--- PASS: TestAccBigipSysProvision_create (2.96s)
=== RUN   TestAccBigipSysProvision_import
--- PASS: TestAccBigipSysProvision_import (2.98s)
=== RUN   TestAccBigipSyssnmp_create
--- PASS: TestAccBigipSyssnmp_create (2.90s)
=== RUN   TestAccBigipSyssnmp_import
--- PASS: TestAccBigipSyssnmp_import (3.15s)
=== RUN   TestValidStringValue
--- PASS: TestValidStringValue (0.00s)
=== RUN   TestInvalidStringValue
--- PASS: TestInvalidStringValue (0.00s)
=== RUN   TestF5NameString
--- PASS: TestF5NameString (0.00s)
=== RUN   TestF5NameSet
--- PASS: TestF5NameSet (0.00s)
=== RUN   TestF5NameList
--- PASS: TestF5NameList (0.00s)
=== RUN   TestValidateEnabledDisabledString
--- PASS: TestValidateEnabledDisabledString (0.00s)
=== RUN   TestValidateReqPrefDisabledString
--- PASS: TestValidateReqPrefDisabledString (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-bigip/bigip	234.685s
SJC-ML-00028512:terraform-provider-bigip shitole$

**Pull request merged**
