### PR TITLE
Add get devices

### PR DESCRIPTION
**Pull request by pescetto**
- Filled out the rest of the Device struct.
- Add the function GetDevices to return a list of bigip devices in the cluster.
- Add a test for the new function

### CODE REVIEW

**Comment by pescetto** [comment]
@scshitole when you have a chance, this PR is ready for review.

**Comment by dannyk81** [comment]
@scshitole this looks useful, can we have this merged?

**Comment by scshitole** [comment]
@pescetto I think the device PR  broke the test for CmDevice
```
ACC=1   go test ./bigip -v  -run=TestAccBigipCm*
=== RUN   TestAccBigipCmDevice_create
--- FAIL: TestAccBigipCmDevice_create (2.27s)
    testing.go:538: Step 0 error: Check failed: Check 3/5 error: bigip_cm_device.test-device: Attribute 'configsync_ip' expected "2.2.2.2", got ""
=== RUN   TestAccBigipCmDevice_import
--- FAIL: TestAccBigipCmDevice_import (3.00s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: bigip_cm_device.test-device
          configsync_ip: "" => "2.2.2.2"
        
        STATE:
        
        bigip_cm_device.test-device:
          ID = test-device
          provider = provider.bigip
          configsync_ip = 
          mirror_ip = 10.10.10.10
          mirror_secondary_ip = 11.11.11.11
          name = test-device
=== RUN   TestAccBigipCmDevicegroup_create
--- FAIL: TestAccBigipCmDevicegroup_create (2.35s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:
        

```

**Comment by pescetto** [comment]
@scshitole I'm running go tests on master (with all my changes and such) and they're all passing:
```bash
$ go test -v
=== RUN   TestDeviceSuite
=== RUN   TestDeviceSuite/TestGetDevices
--- PASS: TestDeviceSuite (0.00s)
    --- PASS: TestDeviceSuite/TestGetDevices (0.00s)
=== RUN   TestNetSuite
=== RUN   TestNetSuite/TestAddInterfaceToVLan
=== RUN   TestNetSuite/TestAddTunnel
=== RUN   TestNetSuite/TestAddVxlan
=== RUN   TestNetSuite/TestCreateRoute
=== RUN   TestNetSuite/TestCreateRouteDomain
=== RUN   TestNetSuite/TestCreateSelfIP
=== RUN   TestNetSuite/TestCreateTrunk
=== RUN   TestNetSuite/TestCreateTunnel
=== RUN   TestNetSuite/TestCreateVLan
=== RUN   TestNetSuite/TestCreateVxlan
=== RUN   TestNetSuite/TestDeleteRoute
=== RUN   TestNetSuite/TestDeleteRouteDomain
=== RUN   TestNetSuite/TestDeleteSelfIP
=== RUN   TestNetSuite/TestDeleteTrunk
=== RUN   TestNetSuite/TestDeleteTunnel
=== RUN   TestNetSuite/TestDeleteVLan
=== RUN   TestNetSuite/TestDeleteVxlan
=== RUN   TestNetSuite/TestGetInterfaces
=== RUN   TestNetSuite/TestGetTunnel
=== RUN   TestNetSuite/TestGetVxlan
=== RUN   TestNetSuite/TestModifyRoute
=== RUN   TestNetSuite/TestModifyRouteDomain
=== RUN   TestNetSuite/TestModifySelfIP
=== RUN   TestNetSuite/TestModifyTrunk
=== RUN   TestNetSuite/TestModifyTunnel
=== RUN   TestNetSuite/TestModifyVLan
=== RUN   TestNetSuite/TestModifyVxlan
=== RUN   TestNetSuite/TestRouteDomains
=== RUN   TestNetSuite/TestRoutes
=== RUN   TestNetSuite/TestSelfIPs
=== RUN   TestNetSuite/TestTrunks
=== RUN   TestNetSuite/TestTunnels
=== RUN   TestNetSuite/TestVlans
=== RUN   TestNetSuite/TestVxlans
--- PASS: TestNetSuite (0.01s)
    --- PASS: TestNetSuite/TestAddInterfaceToVLan (0.00s)
    --- PASS: TestNetSuite/TestAddTunnel (0.00s)
    --- PASS: TestNetSuite/TestAddVxlan (0.00s)
    --- PASS: TestNetSuite/TestCreateRoute (0.00s)
    --- PASS: TestNetSuite/TestCreateRouteDomain (0.00s)
    --- PASS: TestNetSuite/TestCreateSelfIP (0.00s)
    --- PASS: TestNetSuite/TestCreateTrunk (0.00s)
    --- PASS: TestNetSuite/TestCreateTunnel (0.00s)
    --- PASS: TestNetSuite/TestCreateVLan (0.00s)
    --- PASS: TestNetSuite/TestCreateVxlan (0.00s)
    --- PASS: TestNetSuite/TestDeleteRoute (0.00s)
    --- PASS: TestNetSuite/TestDeleteRouteDomain (0.00s)
    --- PASS: TestNetSuite/TestDeleteSelfIP (0.00s)
    --- PASS: TestNetSuite/TestDeleteTrunk (0.00s)
    --- PASS: TestNetSuite/TestDeleteTunnel (0.00s)
    --- PASS: TestNetSuite/TestDeleteVLan (0.00s)
    --- PASS: TestNetSuite/TestDeleteVxlan (0.00s)
    --- PASS: TestNetSuite/TestGetInterfaces (0.00s)
    --- PASS: TestNetSuite/TestGetTunnel (0.00s)
    --- PASS: TestNetSuite/TestGetVxlan (0.00s)
    --- PASS: TestNetSuite/TestModifyRoute (0.00s)
    --- PASS: TestNetSuite/TestModifyRouteDomain (0.00s)
    --- PASS: TestNetSuite/TestModifySelfIP (0.00s)
    --- PASS: TestNetSuite/TestModifyTrunk (0.00s)
    --- PASS: TestNetSuite/TestModifyTunnel (0.00s)
    --- PASS: TestNetSuite/TestModifyVLan (0.00s)
    --- PASS: TestNetSuite/TestModifyVxlan (0.00s)
    --- PASS: TestNetSuite/TestRouteDomains (0.00s)
    --- PASS: TestNetSuite/TestRoutes (0.00s)
    --- PASS: TestNetSuite/TestSelfIPs (0.00s)
    --- PASS: TestNetSuite/TestTrunks (0.00s)
    --- PASS: TestNetSuite/TestTunnels (0.00s)
    --- PASS: TestNetSuite/TestVlans (0.00s)
    --- PASS: TestNetSuite/TestVxlans (0.00s)
PASS
ok  	_/Users/mpescetto/git/pescetto/go-bigip	0.474s
```

I also don't see that test at all on master:
```bash
$ grep 'TestAccBigipCmDevice' -r ./                                                                                                                                     
$
```

Is that a new test you're adding? It might be easier chatting in the slack room if you're on the `f5CloudSolutions` workspace.

**Comment by scshitole** [comment]
@pescetto on slack now

**Pull request merged**
